"""Central tool registry.

The registry is the single gate between model output and execution. A tool runs
only if (a) its name is registered and (b) its arguments validate against the
tool's Pydantic schema. Unknown names are rejected and recorded, never guessed
at or executed.
"""

from __future__ import annotations

import asyncio
import json
import logging
from pathlib import Path
from typing import Any, Iterable, Sequence

from agent.state import ToolCallRequest, ToolResult
from agent.tools.base import BaseTool
from agent.tools.dosage_lookup_tool import DosageLookupTool
from agent.tools.drug_interaction_tool import DrugInteractionTool
from agent.tools.literature_search_tool import LiteratureSearchTool
from agent.tools.vector_search_tool import VectorSearchTool
from agent.tools.web_search_tool import WebSearchTool
from config.settings import Settings, get_settings

logger = logging.getLogger(__name__)

SCHEMA_EXPORT_PATH = Path(__file__).resolve().parents[2] / "config" / "tool_schemas.json"


class ToolRegistry:
    """Holds tool instances and mediates every invocation."""

    def __init__(self, tools: Iterable[BaseTool] | None = None, settings: Settings | None = None) -> None:
        self._settings = settings or get_settings()
        self._tools: dict[str, BaseTool] = {}
        for tool in tools or []:
            self.register(tool)

    # ------------------------------------------------------------ management
    def register(self, tool: BaseTool, *, override: bool = False) -> None:
        if not tool.name or tool.name == "base":
            raise ValueError("Tool must define a unique non-default name")
        if tool.name in self._tools and not override:
            raise ValueError(f"Tool '{tool.name}' is already registered")
        self._tools[tool.name] = tool

    def unregister(self, name: str) -> None:
        self._tools.pop(name, None)

    def get(self, name: str) -> BaseTool | None:
        return self._tools.get(name)

    def has(self, name: str) -> bool:
        return name in self._tools

    @property
    def names(self) -> list[str]:
        return sorted(self._tools)

    def __len__(self) -> int:
        return len(self._tools)

    def __contains__(self, name: object) -> bool:
        return isinstance(name, str) and name in self._tools

    # --------------------------------------------------------------- schemas
    def describe_all(self) -> list[dict[str, Any]]:
        return [self._tools[name].describe() for name in self.names]

    def function_specs(self, exclude_network: bool = False) -> list[dict[str, Any]]:
        """Groq/OpenAI-style function specs for the registered tools."""
        specs: list[dict[str, Any]] = []
        for name in self.names:
            tool = self._tools[name]
            if exclude_network and tool.requires_network:
                continue
            specs.append(tool.to_function_spec())
        return specs

    def planner_catalog(self) -> str:
        """Compact human-readable catalogue injected into the planner prompt."""
        lines = []
        for name in self.names:
            tool = self._tools[name]
            props = tool.argument_schema().get("properties", {})
            required = set(tool.argument_schema().get("required", []))
            arg_summary = ", ".join(
                f"{key}{'' if key in required else '?'}:{spec.get('type', 'any')}"
                for key, spec in props.items()
            )
            lines.append(f"- {name}({arg_summary}): {tool.description.strip()}")
        return "\n".join(lines)

    def export_schemas(self, path: Path | None = None) -> Path:
        """Write the tool catalogue to ``config/tool_schemas.json``."""
        path = path or SCHEMA_EXPORT_PATH
        path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "_comment": "Generated by ToolRegistry.export_schemas(); do not hand-edit.",
            "tools": self.describe_all(),
        }
        path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
        return path

    # ------------------------------------------------------------- execution
    def validate_call(self, call: ToolCallRequest) -> str | None:
        """Return an error string if the call is not executable, else ``None``."""
        tool = self._tools.get(call.name)
        if tool is None:
            return f"Unknown tool '{call.name}'. Registered: {self.names}"
        if tool.requires_network and not self._settings.enable_network_tools:
            return f"Tool '{call.name}' requires network access, which is disabled."
        try:
            tool.validate_arguments(call.arguments)
        except Exception as exc:  # noqa: BLE001
            return str(exc)
        return None

    async def execute(self, call: ToolCallRequest) -> ToolResult:
        """Execute a single validated call."""
        tool = self._tools.get(call.name)
        if tool is None:
            return ToolResult(
                tool=call.name,
                ok=False,
                arguments=dict(call.arguments),
                error=f"Unknown tool '{call.name}' - execution refused.",
            )
        return await tool.execute(call.arguments, timeout=self._settings.tool_timeout)

    async def execute_many(self, calls: Sequence[ToolCallRequest]) -> list[ToolResult]:
        """Execute independent tool calls concurrently."""
        if not calls:
            return []
        if len(calls) == 1:
            return [await self.execute(calls[0])]
        return list(await asyncio.gather(*(self.execute(call) for call in calls)))

    def execute_sync(self, calls: Sequence[ToolCallRequest]) -> list[ToolResult]:
        """Blocking helper for scripts and tests."""
        return asyncio.run(self.execute_many(calls))


def build_default_registry(settings: Settings | None = None) -> ToolRegistry:
    """Registry containing every production tool."""
    settings = settings or get_settings()
    registry = ToolRegistry(settings=settings)
    registry.register(VectorSearchTool(settings=settings))
    registry.register(DrugInteractionTool(settings=settings))
    registry.register(DosageLookupTool(settings=settings))
    registry.register(LiteratureSearchTool(settings=settings))
    registry.register(WebSearchTool(settings=settings))
    return registry
